---
title: "IRT calibration"
author: "Mubarak Mojoyinola, Geraldo Padilla"
date: "03-22-2022"
output: html_document
---

```{r, include=FALSE, include=FALSE}
knitr::opts_chunk$set(message = FALSE, fig.width = 5, fig.height = 3)
```

```{r, message=FALSE, include=FALSE}
library(tidyverse)
library(difR)
library(ltm)
library(mirt)
```

```{r}
setwd("C:/Users/Lenovo/OneDrive - University of Iowa/PhD portfolio/2. Courses/Spring 2022/PSQF62620001 Item Response Theory (Deborah Harris)/12 Polytomous/12 homework/")
```

```{r}
data <- read.fwf("C:/Users/Lenovo/OneDrive - University of Iowa/PhD portfolio/2. Courses/Spring 2022/PSQF62620001 Item Response Theory (Deborah Harris)/12 Polytomous/12 homework/simdata_I40.txt", widths = c(10, rep(1,40)))
colnames(data) <- c('ID', paste0('MC', seq(1,36)), paste('CR', seq(1,4)))
```

# Calibration using the 3-PL Model for MC items
```{r, warning=FALSE, message=FALSE}
data1 <- data[,2:37]
data2 <- data[,38:41]

m3pl_mc <- itemParEst(data1, model = "3PL", engine = "ltm")
m3pl_mc_df = data.frame(m3pl)

m3pl_cr <- gpcm(data[], constraint = c("gpcm"), IRT.param = TRUE, 
    start.val = NULL, na.action = NULL, control = list())
coef(m3pl_cr)
```

# Example 2: using random groups
```{r, warning=FALSE, message=FALSE}
data2 <- data[1:4000, paste0("math",seq(1,60))]
data2_A <- data2[1:2000,c(seq(1,60, 2))]
data2_B <- data2[2001:4000,c(seq(2,60, 2))]

m2_A <- itemParEst(data2_A, model = "3PL", engine = "ltm")
m2_B <- itemParEst(data2_B, model = "3PL", engine = "ltm")

m2_A_df = data.frame(m2_A)
m2_B_df = data.frame(m2_B)

head(m2_A_df[, 1:3])
head(m2_B_df[, 1:3])
```

# Example 3: using concurrent calibration (Common items)
```{r, warning=FALSE, message=FALSE}
data2 <- data[1:4000, paste0("math",seq(1,60))]
data3_A <- data2[1:2000,c(seq(1,16), seq(17, 60, 2))]
data3_B <- data2[2001:4000,c(seq(1,16), seq(18, 60, 2))]

#matching colnames
colnames(data3_A) <- c(paste0('math', seq(1,38)))
colnames(data3_B) <- c(paste0('math', seq(1,38)))

data_3_AB <- rbind(data3_A, data3_B)

m3_AB <- itemParEst(data_3_AB, model = "3PL", engine = "ltm")
m3_AB_df = data.frame(m3_AB)


m3_A <- itemParEst(data3_A, model = "3PL", engine = "ltm")
m3_B <- itemParEst(data3_B, model = "3PL", engine = "ltm")

m3_A_df = data.frame(m3_A)
m3_B_df = data.frame(m3_B)

head(m3_A_df[, 1:3])
head(m3_B_df[, 1:3])
```

# Example 4: using separate calibration (Common items)
```{r, warning=FALSE, message=FALSE}
data2 <- data[1:4000, paste0("math",seq(1,60))]
data3_A <- data2[1:2000,c(seq(1,16), seq(17, 60, 2))]
data3_B <- data2[2001:4000,c(seq(1,16), seq(18, 60, 2))]

m3_A <- itemParEst(data3_A, model = "3PL", engine = "ltm")
m3_B <- itemParEst(data3_B, model = "3PL", engine = "ltm")

m3_A_df = data.frame(m3_A)
m3_B_df = data.frame(m3_B)
```

Using the Mean-Sigma approach, we can transform the item parameters from Form B into form B scale
```{r, warning=FALSE, message=FALSE}
m_sd_A <- m3_A_df[1:16,]%>%
  dplyr::select(a, b)%>%
  summarise(
    mean_a = mean(a),
    sd_a = sd(a),
    mean_b = mean(b),
    sd_b = sd(b))

m_sd_B <- m3_B_df[1:16,]%>%
  dplyr::select(a, b)%>%
  summarise(
    mean_a = mean(a),
    sd_a = sd(a),
    mean_b = mean(b),
    sd_b = sd(b))

A = m_sd_B$sd_b/m_sd_A$sd_b
B = m_sd_B$mean_b - (A * m_sd_A$mean_b)

m3_A_df_SC <- m3_A_df[,1:3]%>%
  mutate(
    new_a = a/A,
    new_b = A*b + B)
```
